### ISSUE TITLE
Need wider product images

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-store-app#24]
See attached screen shot.

<img width="600" alt="screen shot 2015-10-23 at 10 12 02" src="https://cloud.githubusercontent.com/assets/135765/10707952/dac52b48-79f9-11e5-9928-fcdb77b37c01.png">

**Comment by BlueRiverInteractive** [comment]
Works fine on iOS . Seems to be a bug on Android.

**Comment by ntherning** [comment]
Yes. It looks like product images are placed too far to the left on android?

**Comment by BlueRiverInteractive** [comment]
I just checked it. It seems to be related to the high resolution of the images. One images seems to work, but then the others also fail. I also get an OutOfMemoryError when decoding the high resolution graphics on my Galaxy S3

**Comment by BlueRiverInteractive** [comment]
```Java
java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
            at org.robovm.store.util.Images.saveBitmap(Images.java:80)
            at org.robovm.store.util.Images.fromUrl(Images.java:71)
            at org.robovm.store.util.Images.setImageFromUrlAsync(Images.java:40)
```
Happens every now and then, not always.

**Comment by ntherning** [comment]
We changed the male grey to be wider. But it I didn't see a difference
after that when launching in sim. But you say it'll help if all are wider?

**Comment by ntherning** [comment]
Works now. Was a cache problem on the Android device.
